# Generated by Django 4.2.7 on 2023-12-07 02:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='role',
            field=models.IntegerField(choices=[(0, 'Stage Owner'), (1, 'Member'), (2, 'Project Manager')], default=2, verbose_name='Role'),
        ),
        migrations.AlterUniqueTogether(
            name='userproject',
            unique_together={('user', 'project')},
        ),
    ]
