# Generated by Django 4.2.7 on 2023-12-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='stage_id',
            new_name='stage',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'Resolved'), (3, 'Rejected')], default=0, verbose_name='Status'),
        ),
    ]
