# Generated by Django 4.2.7 on 2023-12-08 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_userproject_role_and_more'),
        ('app', '0002_stage_deleted_at_stage_status_alter_userproject_role'),
    ]

    operations = [
    ]
